\c darat;

GRANT CONNECT ON DATABASE darat TO macan;
GRANT USAGE ON SCHEMA public TO macan;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO macan;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO macan;
