\c laut;

GRANT CONNECT ON DATABASE laut TO paus;
GRANT USAGE ON SCHEMA public TO paus;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO paus;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON TABLES TO paus;
